:concurrency: 30
:logfile: /var/log/sidekiq/sidekiq.log
:queues:
  - [default, 5]
  - [blogs_scraper, 4]
  - [apns_notifications, 10]
  - [notifications, 10]
  - [emails, 10]
  - [newsletter, 5]
  - [activities, 10]